services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    volumes:
      - frontend_build:/frontend/build

  nginx:
    image: nginx:alpine
    ports:
      - 80:3000
    volumes:
      - ./nginx/setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
    depends_on:
      - frontend
      - backend

volumes:
  frontend_build:
