# dev config
services:
  backend:
    build: ./backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
      - frontend_build:/frontend/build

  nginx:
    image: nginx:alpine
    ports:
      - 80:3000
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  node_modules:
