# prod config
services:
  backend:
    image: jijieliu/signature_detection_backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend

  frontend:
    image: jijieliu/signature_detection_frontend
    command: npm run build
    volumes:
      - frontend_build:/frontend/build

  nginx:
    image: nginx:alpine
    ports:
      - 80:3000
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/frontend
    depends_on:
      - frontend
      - backend

volumes:
  frontend_build:
