# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1
  python: circleci/python@1.4
  docker: circleci/docker@1.6.0

executors:
  frontend-executor:
    docker:
      - image: cimg/node:14.17.0
        auth:
          username: jijieliu
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/signature_detection_app/frontend 

  backend-executor:
    docker:
      - image: jijieliu/signature_detection_backend
        auth:
          username: jijieliu
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/signature_detection_app/backend 

jobs:
  frontend-prepare-dependencies:
    executor: frontend-executor
    steps:
      - checkout:
          path: ~/signature_detection_app
      - run:
          name: Compute version number
          command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
      - node/install-packages
      - store_artifacts:
          path: package.json
      - persist_to_workspace:
          root: frontend-workspace
          paths:
            - .
      
  frontend-test: 
    executor: frontend-executor
    steps:
      - attach_workspace:
          at: frontend-workspace
      - run:
          name: Run tests
          command: npm test
    
  backend-test:
    executor: backend-executor
    steps:
      - checkout:
          path: ~/signature_detection_app
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  test: 
    jobs:
      - frontend-test
      - backend-test