# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1
  python: circleci/python@1.2

executors:
  frontend-executor:
    docker:
      - image: cimg/node:14.17.0
    working_directory: ~/signature_detection_app/frontend 

  backend-executor:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/signature_detection_app/backend 

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  frontend-test: 
    executor: frontend-executor
    steps:
      # Checkout the code as the first step.
      - checkout:
          path: ~/signature_detection_app
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages
      # If you are using yarn instead npm, remove the line above and uncomment the two lines below.
      # - node/install-packages:
      #     pkg-manager: yarn 
      - run:
          name: Run tests
          command: npm test
    
  backend-test:
    executor: backend-executor
    steps:
      - checkout:
          path: ~/signature_detection_app
      
      - python/install-packages:
          pkg-manager: pip
      
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  test: 
    jobs:
      - frontend-test
      - backend-test
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
