FROM python:3.8

ENV PYTHONUNBUFFERED=1

WORKDIR /api

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .
EXPOSE 8000
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]